name: "Create cluster using KinD"
on:
  - workflow_dispatch
  - pull_request
  - push

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install KinD
        run: |
          curl -Lo https://kind.sigs.k8s.io/dl/v0.10.0/kind-linux-amd64
          chmod +x ./kind
          mkdir $HOME/bin
          mv ./kind $HOME/bin/kind
          "$HOME/bin" >> $GITHUB_PATH
      - name: Cluster Info
        run: |
          which kind
          kind cluster create
          kubectl cluster-info
          kubectl get pods -n kube-system
      - name: Deploy a Pod
        run: |
          kubectl apply -f pod.yml
          kubectl get po