name: "Create cluster using KinD"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |
          echo "First!"